home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^login/', views.user_login, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    ]

planvore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home'))
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

home/forms.py
from django import forms
from django.core import validators
from home.models import UserProfileInfo
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.models import User


gender_choices = [('male', 'Male'), ('female', 'Female')]

sec_questions = [("nickname", 'What was your childhood nickname?'),
                 ("bff", "What is the name of your favorite childhood friend?"),
                 ("city", "In what city or town did your mother and father meet?"),
                 ("middle", "What is the middle name of your oldest child?"),
                 ("team", "What is your favorite team?"),
                 ("movie", "What is your favorite movie?"),
                 ("sport", "What was your favorite sport in high school?"),
                 ("food", "What was your favorite food as a child?")
                 ]


class UserForm(forms.ModelForm):
    model = User
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control input-group-lg bg-transparent light',
            'placeholder': 'Enter your username.',
            'id':'place'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class':'form-control input-group-lg bg-transparent light',
            'placeholder':'Enter your password.',
            'id':'place'
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class':'form-control input-group-lg bg-transparent light',
            'placeholder':'Enter your email.',
            'id':'place'
        }
    ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    portfolio = forms.URLField(widget=forms.URLInput(
        attrs={
            'class': 'form-control input-group-lg bg-transparent light',
            'placeholder':'Enter link to your profile.',
            'id':'place'
        }
    ))
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs= {
                'id':"drop_zone",
                'class':"FileUpload",
                'accept':'.jpg,.png,.gif',
                'onchange':'handleFileSelect(this)'
        }
    ))

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio', 'picture')


#
# class LoginForm(forms.ModelForm):
#     first_name = forms.CharField(128, validators=[validators.MaxLengthValidator(20)])
#     last_name = forms.CharField(128)
#     username = forms.CharField(128)
#     email_ad = forms.EmailField(label="Email Address")
#     email_ver = forms.EmailField(label="Email Address Confirmation")
#     password = forms.CharField(widget=forms.PasswordInput(render_value=True))
#     password_ver = forms.CharField(widget=forms.PasswordInput(render_value=True))
#     gender = forms.ChoiceField(choices=gender_choices, widget=forms.RadioSelect())
#     security_question = forms.ChoiceField(choices=sec_questions)
#     question_answer = forms.CharField(128)
#     terms_check = forms.BooleanField(required=True, label="I have read the terms!")
#     no_bot = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])
#
#     class Meta:
#         model = UserData
#         fields = '__all__'
#
#     def clean(self):
#         all_clean = super().clean()
#         email_ad = all_clean.get('email_ad')
#         email_ver = all_clean.get('email_ver')
#
#         if email_ad != email_ver:
#             raise forms.ValidationError("Please correct to matching emails.")
#
#         try:
#             validate_email(email_ad)
#
#         except ValidationError as e:
#             print("oops! wrong email")
#
#         else:
#             print("hooray! email is valid")

home/views.py
from . import forms
from django.shortcuts import render
from . import models
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, ListView, DetailView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse


class IndexView(TemplateView):
    template_name = 'home/index.html'


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'home/register.html', {'user_form': user_form,
                                                  'profile_form': profile_form,
                                                  'registered': registered
                                                  })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('home:index'))

            else:
                return HttpResponse('Not logged in!')

        else:
            print("failed tried to login and failed")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse('invalid login details suplied')

    else:
        return render(request, 'home/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


@login_required
def profile(request):
    return render(request, 'home/profile.html', {})

# @login_required
# class UserProfileDetailView(DetailView):
#     model = UserProfileInfo

templates/home/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load widget_tweaks %}

<html lang="en">

  <head>

  {% block head %}

      {% block meta %}
        <!-- Required meta tags -->
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

            <meta name="msapplication-TileColor" content="#ffffff">
            <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
            <meta name="theme-color" content="#ffffff">

      {% endblock meta %}


      {% block stylesheets %}

        <!-- CSS -->
          <link rel="stylesheet" href="{% static 'css/css.css' %}"/>
          <link href="https://fonts.googleapis.com/css?family=Syncopate" rel="stylesheet"/>
          <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

          <!--Import Google Icon Font-->
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


          {#CSS LIBRARIES#}


          {#<!-- MARIALIZE - Compiled and minified CSS -->#}
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">



            {#FAVICONS#}
            <link rel="apple-touch-icon" sizes="57x57" href={% static "images/favicon/apple-icon-57x57.png" %}>
            <link rel="apple-touch-icon" sizes="60x60" href={% static "images/favicon/apple-icon-60x60.png" %}>
            <link rel="apple-touch-icon" sizes="72x72" href={% static "images/favicon/apple-icon-72x72.png" %}>
            <link rel="apple-touch-icon" sizes="76x76" href={% static "images/favicon/apple-icon-76x76.png" %}>
            <link rel="apple-touch-icon" sizes="114x114" href={% static "images/favicon/apple-icon-114x114.png" %}>
            <link rel="apple-touch-icon" sizes="120x120" href={% static "images/favicon/apple-icon-120x120.png" %}>
            <link rel="apple-touch-icon" sizes="144x144" href={% static "images/favicon/apple-icon-144x144.png" %}>
            <link rel="apple-touch-icon" sizes="152x152" href={% static "images/favicon/apple-icon-152x152.png" %}>
            <link rel="apple-touch-icon" sizes="180x180" href={% static "images/favicon/apple-icon-180x180.png" %}>
            <link rel="icon" type="image/png" sizes="192x192"  href={% static "images/favicon/android-icon-192x192.png" %}>
            <link rel="icon" type="image/png" sizes="32x32" href={% static "images/favicon/favicon-32x32.png" %}>
            <link rel="icon" type="image/png" sizes="96x96" href={% static "images/favicon/favicon-96x96.png" %}>
            <link rel="icon" type="image/png" sizes="16x16" href={% static "images/favicon/favicon-16x16.png" %}>
            <link rel="manifest" href={% static "images/favicon/manifest.json" %}>


      {% endblock stylesheets %}

            <title>Planvore</title>

  {% endblock head %}



  </head>

  <body>

  {% block body %}



      {% block top_navigation %}
          {% include "home/top_nav.html" %}
      {% endblock top_navigation %}



      {% block content %}

      {% endblock content %}


      {% block footer %}

           {% include "home/footer.html" %}

      {% endblock footer %}


      {% block scripts %}



        {#J-QUERY#}
        <script language="JavaScript" type="text/javascript" src="{% static 'js/jquery-3.2.1.js' %}"></script>
        <script language="JavaScript" type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

           {#JS FROM CSS LIBRARIES#}
           <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

      {% endblock scripts %}


    {% endblock body %}

  </body>

</html>

templates/home/footer.html
<!-- The content of your page would go here. -->
{% load staticfiles %}

<div id="footer_js">
		<!-- The content of your page would go here. -->

		<footer class="footer-distributed">

			<div class="footer-left">

				<h3>Company<span>logo</span></h3>

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<a href="#">Blog</a>
					·
					<a href="#">Pricing</a>
					·
					<a href="#">About</a>
					·
					<a href="#">Faq</a>
					·
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">Company Name &copy; 2015</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>21 Revolution Street</span> Paris, France</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+1 555 123456</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@company.com">support@company.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the company</span>
					Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>

</div>

templates/home/index.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}

            <div class="jumbotron">

            <h1 class="display-3">A new age of financial planning and control. </h1>
                <p class="lead">A toolbox of solutions to master personal budget planning to big business KPI management. </p>

                <hr class="my-2">
                <p>More info</p>
                <p class="lead">
                <a class="btn btn-dark btn-lg" href="{% url 'home:login' %}" role="button">Get started!</a>
                </p>
            </div>

            <div class="container">

            {{ inject_me }}

            <div class="row">

                <div class="col-lg-6" >
                     <p>  Mussum Ipsum, cacilds vidis litro abertis. Aenean aliquam molestie leo, vitae iaculis nisl. Sapien in monti palavris qui num significa nadis i pareci latim. A ordem dos tratores não altera o pão duris. Interagi no mé, cursus quis, vehicula ac nisi.</p>
                </div>

                <div class="col-lg-6">
                     <p>  Si num tem leite então bota uma pinga aí cumpadi! Não sou faixa preta cumpadi, sou preto inteiris, inteiris. Manduma pindureta quium dia nois paga. Quem num gosta di mé, boa gentis num é.</p>
                </div>

            </div>
            </div>

{% endblock content %}

templates/home/login.html
{% extends "home/base.html" %}

{% block content %}

<div class="box">

    <div id="header">
        <div id="cont-lock"><i class="fa fa-lock fa-2x lock" aria-hidden="true"></i></div>
        <div id="bottom-head"><h1 id="logintoregister">Login</h1></div>
    </div>

   <form action="{% url 'home:login' %}" id='login_form' method="post">
        {% csrf_token %}

       <div class="group">
        <input class="input-material" type="text" required>
        <span class="highlight"></span>
        <span class="bar"></span>
        <label>Username</label>
        </div>

    <div class="group">
        <input class="input-material" type="password" required>
        <span class="highlight"></span>
        <span class="bar"></span>
        <label>Password</label>
    </div>

        <button id="buttonlogintoregister" type="submit">Login</button>
  </form>

        <div id="footer-box"><p class="footer-text">Not a member?<span class="sign-up"> Sign up now</span></p></div>
    </div>


{% endblock content %}

{% comment %}
{% extends 'home/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="form-wrapper">

    <h3>Please Login</h3>

        </br>

      <form action="{% url 'home:login' %}" method="post" class="form">
            {% csrf_token %}

            <div class="form-group">
                <label class="form-label" for="username">Username</label>
                <input name="username" id="first" class="form-input" type="text" />
            </div>

            <div class="form-group">
                <label class="form-label" for="password">Password</label>
                <input name="password" id="last" class="form-input" type="text" />
            </div>


          <input type="submit" class="btn btn-primary" value="Log In">

      </form>

    </div>


{% endblock content %}
{% endcomment %}

templates/home/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/home/register.html
{% extends 'home/base.html' %}
{% load widget_tweaks %}

{% block content %}

    {% if registered %}

    <h1> Thank you for registering! </h1>

    {% else %}

        <div class="container">

        <div id="transparent_box">

            <h1>Register your profile!</h1>

        <form method="post" class="form-group" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="form-group has-error" id="place">

            {{ user_form.as_p }}
            {{ profile_form.portfolio.label}}
            {{ profile_form.portfolio}}



            <div class="container-inner">
            {{ profile_form.picture}}
            <div class="dropZoneOverlay">Click to add a profile picture.</div>

            <input type="submit" name="" class="btn btn-primary" value="Register!">
            </div>

            </div>
        </form>

    {% endif %}

        </div>

        </div>

{% endblock content %}

templates/home/top_nav.html
{% load staticfiles %}

<div class="navbar-fixed-top"
    <nav class="">

        <div class="nav-wrapper">


        <a class="brand-logo" href="{% url 'home:index' %}">
            <img src="../../static/images/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span id="planvore">Planvore</span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
               aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

             <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>


           <i class="fa fa-bars" aria-hidden="true"></i>

        </button>

    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>

            {% if user.is_authenticated %}

            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:register' %}">Register</a>
            </li>

            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Application
                </a>

            <div class="dropdown-menu list-group-item-dark" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#"> Plan your personal budget</a>
                <a class="dropdown-item" href="#"> Build your business plan</a>
                <a class="dropdown-item" href="#"> Set your company KPIs control</a>
            </div>

            </li>

        </ul>

        <ul class="nav navbar-nav navbar-right"
             {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                </li>

             {% endif %}

            <li class="nav-item dropdown my-2 my-sm-0">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My account
                </a>


            <div class="dropdown-menu list-group-item-dark" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#"> Profile </a>
                <a class="dropdown-item" href="#"> My Apps </a>
                <a class="dropdown-item" href="#"> Settings </a>
            </div>

            </li>

        </ul>

    </div>

</nav>